name: Run Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
        
    - name: Pull Docker image
      run: docker pull flaresolverr/flaresolverr
      #docker pull therealbix/flaresolverr #old fix
      #ghcr.io/flaresolverr/flaresolverr:v3.3.17

    - name: Run FlareSolverr
      run: docker run -d --name flaresolverr-container -p 8191:8191 flaresolverr/flaresolverr
      #ghcr.io/flaresolverr/flaresolverr:v3.3.16

    - name: Wait for FlareSolverr to start
      run: sleep 20

    - name: Run scraper
      run: python scraper.py
      
    - name: Show files
      run: ls downloads
